version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy-ci:8bfd4f9d9660a74d495563dc4da92137c9b367c6
    steps:
      - checkout
      - run:
          command: compose-deploy deploy

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          requires: []