version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy-ci:8be492867b3e13383c1ae86b0a1403e0feaa3861
    steps:
      - checkout
      - run:
          command: compose-deploy deploy

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          requires: []