version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy-ci:47fd5df1e9f82528b1bc4ba2f83474b006be7abd
    steps:
      - checkout
      - run:
          command: compose-deploy deploy

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          requires: []