version: 2

jobs:
  deploy:
    docker:
      - image: totakoko/compose-deploy-ci:adec1d447466b96ee8fd65574310fdc78be8bdc1
    steps:
      - checkout
      - run:
          command: compose-deploy deploy

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          requires: []